### ISSUE TITLE
[Feature Request] Playing Liked Songs

### ISSUE THREAD

**Issue by LouisMehring** [fow5040/Flow.Launcher.Plugin.SpotifyPremium#20]
Maybe I just didnt found the command but since Liked Song isnt a typical playlist I cant play it from the command line in Flow Launcher? 
Thanks in advance!

**Comment by erebfaer** [comment]
So I just started using this plugin and decided I needed this feature and set about making it.
Turns out the API doesn't give a nice way to treat saved songs as a playlist.
I did manage to search my liked songs and play individual tracks, but it didn't queue up the rest and for some reason it is slower than any other search. If @fow5040 wants I can make a pull request, but its not really useful IMO.

As a workaround for the playlist though, in the Spotify client Liked Songs playlist you can ctrl+a > right click > add to playlist. You'll need to update it whenever you like new songs though.

**Comment by fow5040** [comment]
@erebfaer thank you for researching this! I'll take your word for it, and yeah from my experience the API is not 1:1 with all features of the client, but it handles most of the primary use cases pretty well.
